import { ArrowRight, MapPin, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const experiences = [
    { title: "Into the wild", copy: "Trade busy days for big skies and quiet trails.", image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85" },
    { title: "Coastal calm", copy: "Follow the sun to shores that slow time down.", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85" },
    { title: "City stories", copy: "Find your favorite corner in a brand-new city.", image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=85" },
];

const Home = () => <div className="overflow-hidden">
    <section className="page-shell relative py-10 sm:py-14 lg:py-20"><div className="absolute -right-36 -top-16 h-96 w-96 rounded-full bg-emerald-200/45 blur-3xl" /><div className="relative grid items-center gap-12 lg:grid-cols-[.94fr_1.06fr]">
        <div className="max-w-xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-emerald-900/10 bg-white/80 px-3.5 py-2 text-xs font-semibold uppercase tracking-[.16em] text-emerald-800"><Sparkles size={14} /> Find your next feeling</div><h1 className="font-display text-5xl leading-[.98] tracking-tight text-slate-900 sm:text-6xl lg:text-7xl">The world feels <em className="font-normal text-emerald-700">closer</em> from here.</h1><p className="mt-7 max-w-md text-base leading-7 text-slate-600 sm:text-lg">Curated places, thoughtful ideas, and a simple way to plan the trip you have been dreaming about.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/destinations" className="inline-flex items-center gap-2 rounded-full bg-emerald-800 px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-emerald-900/20 transition hover:-translate-y-0.5 hover:bg-emerald-900">Explore destinations <ArrowRight size={17} /></Link><Link to="/login" className="rounded-full border border-slate-300 bg-white/70 px-6 py-3.5 text-sm font-semibold text-slate-700 transition hover:border-emerald-700 hover:text-emerald-800">Plan a trip</Link></div></div>
        <div className="relative mx-auto w-full max-w-2xl"><img className="h-[430px] w-full rounded-[2rem] object-cover shadow-2xl shadow-emerald-950/20 sm:h-[570px]" src="https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=90" alt="A traveller looking over a mountain landscape" /><div className="absolute bottom-5 left-5 rounded-2xl bg-white/90 px-4 py-3.5 shadow-lg backdrop-blur sm:bottom-8 sm:left-8"><div className="flex items-center gap-2 text-sm font-bold text-slate-800"><MapPin size={16} className="text-emerald-700" /> Dolomites, Italy</div><p className="mt-1 pl-6 text-xs text-slate-500">A view worth the early start</p></div></div>
    </div></section>
    <section className="page-shell py-20"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Choose your pace</p><h2 className="mt-3 font-display text-4xl text-slate-900 sm:text-5xl">Where will curiosity take you?</h2></div><Link to="/destinations" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-800 hover:text-emerald-950">See all destinations <ArrowRight size={16} /></Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{experiences.map((item) => <Link to="/destinations" key={item.title} className="group overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-900/5 transition duration-300 hover:-translate-y-1 hover:shadow-xl"><img src={item.image} alt="" className="h-64 w-full object-cover transition duration-500 group-hover:scale-105" /><div className="p-6"><h3 className="font-display text-2xl text-slate-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.copy}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-emerald-800">Explore <ArrowRight size={15} /></span></div></Link>)}</div></section>
    <section className="page-shell pb-4"><div className="rounded-[2rem] bg-emerald-800 px-7 py-12 text-center text-white sm:px-12 sm:py-16"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-200">Your next chapter</p><h2 className="mx-auto mt-3 max-w-xl font-display text-4xl leading-tight sm:text-5xl">There is a whole world waiting for you.</h2><Link to="/register" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#f5dca8] px-6 py-3.5 text-sm font-bold text-emerald-950 transition hover:bg-white">Start your journey <ArrowRight size={17} /></Link></div></section>
</div>;
export default Home;
